spring:
  config:
    import:
      - application-mysql.yaml
      - application-jasypt.yaml
      - application-apidoc.yaml
      - application-redis.yaml
  main:
    allow-bean-definition-overriding: true