discord:
  bot:
    token: ENC(z8iC8/kwDf8A4at33IvCEbXG2v8+9XJ3eTCjIlNrwdSPLkFTWF4zekleJZsRnWth4ha+zkUt5QuSbZJd51jZaSi4wznqUVDUCizZF+Mqd1/bLOS5MSR89A==)


    #ENC(CMv2X3iyTq3sZd6OZPkMl2WcrP2rNhbohz9OG+sAL3I=)
