spring:
  config:
    import:
      - application-mysql.yaml
      - application-jasypt.yaml
      - application-apidoc.yaml
      - application-redis.yaml
      - application-discord.yaml
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  async:
    request-timeout: 100000